load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "papercraft_client",
    srcs = ["src/main.c"],
    deps = [
        "//packages/common:common_headers",
        "//packages/simulation:paper_fragment",
    ],
    linkopts = ["-lSDL2", "-lGL", "-lGLU", "-lm"],
    visibility = ["//visibility:public"],
)
