/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_papercraft_explosion_in_range_(int, int);
int on_papercraft_explosion_damage_at_distance(int, int, int);

int on_papercraft_explosion_in_range_(int blast_radius __attribute__((unused)), int distance __attribute__((unused))) {
    return ((blast_radius > 0) && (distance <= blast_radius));
}

int on_papercraft_explosion_damage_at_distance(int max_damage __attribute__((unused)), int blast_radius __attribute__((unused)), int distance __attribute__((unused))) {
    if ((blast_radius <= 0)) {
    return 0;
    } else {
    if ((distance >= blast_radius)) {
    return 0;
    } else {
    double clamped_distance __attribute__((unused)) = ((distance < 0) ? 0 : distance);
    return ((max_damage * (blast_radius - clamped_distance)) / blast_radius);
    }
    }
}

