/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_papercraft_interact_damage_falloff(int, int);

int on_papercraft_interact_damage_falloff(int base_damage __attribute__((unused)), int dist_permille __attribute__((unused))) {
    double clamped __attribute__((unused)) = ((dist_permille > 1000) ? 1000 : ((dist_permille < 0) ? 0 : dist_permille));
    return ((base_damage * (1000 - clamped)) / 1000);
}

