/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int inventory_scrap_id();
int on_papercraft_inventory_stack_max(int);
int on_papercraft_inventory_can_stack(int, int);

int inventory_scrap_id(void) {
    return 1;
}

int on_papercraft_inventory_stack_max(int item_id __attribute__((unused))) {
    if ((item_id == inventory_scrap_id())) {
    return 99;
    } else {
    return 0;
    }
}

int on_papercraft_inventory_can_stack(int existing_item_id __attribute__((unused)), int incoming_item_id __attribute__((unused))) {
    return ((existing_item_id == incoming_item_id) && (existing_item_id > 0));
}

