/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int material_paper();
int item_drop_scrap_id();
int on_papercraft_item_for_object_destroyed(int);

int material_paper(void) {
    return 0;
}

int item_drop_scrap_id(void) {
    return 1;
}

int on_papercraft_item_for_object_destroyed(int material __attribute__((unused))) {
    if ((material == material_paper())) {
    return item_drop_scrap_id();
    } else {
    return 0;
    }
}

