/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int xp_required_for_level(int);
int on_papercraft_level_for_xp(int, int);

int xp_required_for_level(int level __attribute__((unused))) {
    if ((level <= 1)) {
    return 0;
    } else {
    return (xp_required_for_level((level - 1)) + (80 + ((level - 2) * 35)));
    }
}

int on_papercraft_level_for_xp(int level __attribute__((unused)), int total_xp __attribute__((unused))) {
    if ((level >= 20)) {
    return 20;
    } else {
    if ((total_xp >= xp_required_for_level((level + 1)))) {
    return on_papercraft_level_for_xp((level + 1), total_xp);
    } else {
    return level;
    }
    }
}

