/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int note_slot_count();
int on_papercraft_note_slot_valid(int);
int on_papercraft_can_access_note(int, int);

int note_slot_count(void) {
    return 8;
}

int on_papercraft_note_slot_valid(int slot __attribute__((unused))) {
    return ((slot >= 0) && (slot < note_slot_count()));
}

int on_papercraft_can_access_note(int owner_player_id __attribute__((unused)), int requesting_player_id __attribute__((unused))) {
    return (owner_player_id == requesting_player_id);
}

