/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int material_resist_pct(int);
int on_paper_fragment_damage(int, int, int);
int on_paper_fragment_state_for_hp(int, int);

int material_resist_pct(int material __attribute__((unused))) {
    if ((material == 0)) {
    return 0;
    } else {
    if ((material == 1)) {
    return 20;
    } else {
    if ((material == 2)) {
    return 50;
    } else {
    return 75;
    }
    }
    }
}

int on_paper_fragment_damage(int material __attribute__((unused)), int hp __attribute__((unused)), int damage __attribute__((unused))) {
    int effective_damage __attribute__((unused)) = (damage - ((damage * material_resist_pct(material)) / 100));
    if ((effective_damage >= hp)) {
    return 0;
    } else {
    return (hp - effective_damage);
    }
}

int on_paper_fragment_state_for_hp(int hp __attribute__((unused)), int max_hp __attribute__((unused))) {
    if ((hp <= 0)) {
    return 3;
    } else {
    if (((hp * 100) < (max_hp * 25))) {
    return 2;
    } else {
    if (((hp * 100) < (max_hp * 60))) {
    return 1;
    } else {
    return 0;
    }
    }
    }
}

