/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int event_object_destroyed();
int message_object_destroyed();
int on_papercraft_phone_message_for_event(int);

int event_object_destroyed(void) {
    return 1;
}

int message_object_destroyed(void) {
    return 1;
}

int on_papercraft_phone_message_for_event(int event_type __attribute__((unused))) {
    if ((event_type == event_object_destroyed())) {
    return message_object_destroyed();
    } else {
    return 0;
    }
}

