/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_papercraft_pickup_radius_millis();

int on_papercraft_pickup_radius_millis(void) {
    return 1800;
}

