/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_papercraft_slide_jump_boost_permille(int);

int on_papercraft_slide_jump_boost_permille(int speed_milli __attribute__((unused))) {
    if ((speed_milli <= 0)) {
    return 1000;
    } else {
    double raw __attribute__((unused)) = (1000 + (250000 / speed_milli));
    if ((raw > 1400)) {
    return 1400;
    } else {
    if ((raw < 1020)) {
    return 1020;
    } else {
    return raw;
    }
    }
    }
}

