/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_papercraft_move_speed_boost_permille(int);

int on_papercraft_move_speed_boost_permille(int move_rank __attribute__((unused))) {
    return (1000 + (35 * move_rank));
}

