/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_papercraft_can_allocate_talent(int, int);

int on_papercraft_can_allocate_talent(int ability_value __attribute__((unused)), int unspent_points __attribute__((unused))) {
    return ((unspent_points > 0) && (ability_value < 5));
}

