/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int weapon_slot_knife();
int weapon_slot_magnum();
int weapon_slot_ar();
int weapon_slot_shotgun();
int weapon_slot_sniper();
int weapon_slot_katana();
int weapon_slot_count();
int weapon_mod_item_knife();
int weapon_mod_item_magnum();
int weapon_mod_item_ar();
int weapon_mod_item_shotgun();
int weapon_mod_item_sniper();
int weapon_mod_item_katana();
int on_papercraft_weapon_item_slot(int);
int on_papercraft_weapon_switch_allowed(int, int);

int weapon_slot_knife(void) {
    return 0;
}

int weapon_slot_magnum(void) {
    return 1;
}

int weapon_slot_ar(void) {
    return 2;
}

int weapon_slot_shotgun(void) {
    return 3;
}

int weapon_slot_sniper(void) {
    return 4;
}

int weapon_slot_katana(void) {
    return 5;
}

int weapon_slot_count(void) {
    return 6;
}

int weapon_mod_item_knife(void) {
    return 2;
}

int weapon_mod_item_magnum(void) {
    return 3;
}

int weapon_mod_item_ar(void) {
    return 4;
}

int weapon_mod_item_shotgun(void) {
    return 5;
}

int weapon_mod_item_sniper(void) {
    return 6;
}

int weapon_mod_item_katana(void) {
    return 7;
}

int on_papercraft_weapon_item_slot(int item_id __attribute__((unused))) {
    if ((item_id == weapon_mod_item_knife())) {
    return weapon_slot_knife();
    } else {
    if ((item_id == weapon_mod_item_magnum())) {
    return weapon_slot_magnum();
    } else {
    if ((item_id == weapon_mod_item_ar())) {
    return weapon_slot_ar();
    } else {
    if ((item_id == weapon_mod_item_shotgun())) {
    return weapon_slot_shotgun();
    } else {
    if ((item_id == weapon_mod_item_sniper())) {
    return weapon_slot_sniper();
    } else {
    if ((item_id == weapon_mod_item_katana())) {
    return weapon_slot_katana();
    } else {
    return -1;
    }
    }
    }
    }
    }
    }
}

int on_papercraft_weapon_switch_allowed(int owned_mask __attribute__((unused)), int requested_slot __attribute__((unused))) {
    if ((requested_slot < 0)) {
    return 0;
    } else {
    if ((requested_slot >= weapon_slot_count())) {
    return 0;
    } else {
    if ((requested_slot == weapon_slot_knife())) {
    return 1;
    } else {
    return ((owned_mask & (1 << requested_slot)) != 0);
    }
    }
    }
}

